import Head from "next/head";
// import styles from "@/components/styles/Home.module.css";
import HomeComponent from "../components/home/HomeComponent";
import { useTheme } from "../context/ThemeModeContext";


export default function Home() {
  const { darkMode, handleToggleTheme } = useTheme();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={darkMode ? { color: "white", backgroundColor: 'black' } : { color: "black", backgroundColor: 'white' }}>
      <div>
      <button onClick={handleToggleTheme}>
        Toggle Theme (Dark Mode: {darkMode ? 'On' : 'Off'})
      </button>
    </div>
          <HomeComponent />
          {/* <div className={styles.center}>
            <Image
              className={styles.logo}
              src="/next.svg"
              alt="Next.js Logo"
              width={180}
              height={37}
              priority
            />
            <div className={styles.thirteen}>
              <Image
                src="/thirteen.svg"
                alt="13"
                width={40}
                height={31}
                priority
              />
            </div>
          </div> */}
        </main>
    </>
  );
}
